version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    networks:
      - app-network
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    expose:
      - "9000" 

  webserver:
    image: nginx:latest
    container_name: laravel_nginx
    depends_on:
      - app
    ports:
      - "2025:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
