services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www
      - ./odcapp-firebase.json:/home/thatsbass/Bureau/study-app/odcapp-firebase.json
    ports:
      - "3000:8000"
    networks:
      - app-network
    environment:
      - DB_CONNECTION=pgsql
      - DATABASE_URL=${DATABASE_URL}
      - FIREBASE_KEY_BASE64=${FIREBASE_KEY_BASE64}
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - FIREBASE_CREDENTIALS=/var/www/odcapp-firebase.json
      - QUEUE_CONNECTION=database

networks:
  app-network:
    driver: bridge
