version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    networks:
      - app-network
    environment:
      - DB_CONNECTION=pgsql
      - DATABASE_URL=${DATABASE_URL}
      - FIREBASE_KEY_BASE64:${FIREBASE_KEY_BASE64}
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - FIREBASE_CREDENTIALS=/var/www/odcapp-firebase.json
      - QUEUE_CONNECTION=database
    expose:
      - "9000" 

  webserver:
    image: nginx:latest
    container_name: laravel_nginx
    depends_on:
      - app
    ports:
      - "2025:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
